### ISSUE TITLE
Where can we find mods for this

### ISSUE THREAD

**Issue by zrm9901** [ppkantorski/Mod-Alchemist#1]
In the readme it says to look in the shared documentation, but I cant find that anywhere, do we use our own mods from gamebanana and if so do what is the naming scheme?

**Comment by ppkantorski** [comment]
See [contents](https://github.com/ppkantorski/Mod-Alchemist/tree/main/Mod%20Alchemist/contents) and [pchtxts](https://github.com/ppkantorski/Mod-Alchemist/tree/main/Mod%20Alchemist/pchtxts) for formatting.  Yes you can add in your own content mods.  Exefs patches (managed from their direct location) will require the same naming schema as pchtxts (`{TITLE_NAME} - {MOD_NAME}`) to be displayed / sorted properly, but you can still toggle them either way.

I'll share the format here as well to make it easier.

For pchtxt's.
`./pchtxts/{TITLE_NAME} - {MOD_NAME}/{VERSION}.pchtxt` 

For content mods.
`./contents/{TITLE_NAME} - {MOD_NAME}/{TITLE_ID}/{MODS_CONTENT}`

where `./` is the path to the `Mod Alchemist` package.

In order for proper management of contents mods for games, you will need to make sure you are installing / managing the mods directly from within Mod Alchemist (the `contents` folder within the directory) and not just directly installing them in the atmosphere `contents` folder.  Otherwise it will not recognize which mods have duplicate files and such when toggling them.
